name: Artifact Bundle

on: 
  schedule: 
    # Daily at 8:20 UTC
    - cron: '20 8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: Test
    runs-on: macOS-13
    steps:
    - name: Get latest version
      run: |
          echo "$(gh release list -R gigabitcoin/template-plugin -L 1)"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
