name: Check GitHub Release

on: 
  schedule: 
    # Daily at 8:20 UTC
    - cron: '20 8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: Check GitHub Release
    runs-on: macOS-13
    steps:
    - name: Get latest version
      run: |
          echo "TEMPLATE_RELEASE=$(gh release list -R gigabitcoin/template-plugin -L 1)" >> $GITHUB_ENV
          echo "BINARY_RELEASE=$(gh release list -R evilmartians/lefthook -L 1)" >> $GITHUB_ENV
          if [[ "$TEMPLATE_RELEASE" == "$BINARY_RELEASE" ]]
          then
              echo "RUN_PUBLISH=false" >> $GITHUB_ENV
          else
              echo "RUN_PUBLISH=true" >> $GITHUB_ENV
          fi
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Print Variables
      run: |
          echo $TEMPLATE_RELEASE
          echo $BINARY_RELEASE
    - name: Print Conditionally
      run: |
          echo $TEMPLATE_RELEASE
          echo $BINARY_RELEASE
      if: ${{ RUN_PUBLISH }}