name: Check GitHub Release

on: 
  schedule: 
    # Daily at 8:20 UTC
    - cron: '20 8 * * *'
  # Enables manually running this workflow from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: Check GitHub Release
    runs-on: macOS-13
    env:
      BINARY_REPO: evilmartians/lefthook
      PLUGIN_REPO: gigabitcoin/template-plugin
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Get lastest binary and plugin versions
      run: |
          SEMANTIC_VERSIONING_REGEX="(v[0-9]+\.[0-9]+\.[0-9]+)|(0\.[0-9]+\.[0-9]+)"

          PLUGIN_RELEASE=$(gh release list -R gigabitcoin/template-plugin -L 1)
          BINARY_RELEASE=$(gh release list -R evilmartians/lefthook -L 1)

          echo "PLUGIN_VERSION=$(echo $PLUGIN_RELEASE | grep -oE $SEMANTIC_VERSIONING_REGEX | head -n1)" >> $GITHUB_ENV
          echo "BINARY_VERSION=$(echo $BINARY_RELEASE | grep -oE $SEMANTIC_VERSIONING_REGEX | head -n1)" >> $GITHUB_ENV
    - uses: ./.github/workflows/publish-artifact-bundle.yml
      with:
        plugin_version: ${{ env.PLUGIN_VERSION }}
        plugin_repo: ${{ env.PLUGIN_REPO }}
      if: ${{ env.PLUGIN_VERSION == env.BINARY_VERSION }}