name: Publish Artifact Bundle

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Publish Artifact Bundle
    runs-on: macOS-13
    steps:
    - name: Get latest version
      run: |
          echo "$(gh release list -R gigabitcoin/template-plugin -L 1)"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}