name: Publish Artifact Bundle

on:
  workflow_call:
    inputs:
      binary_version:
        required: true
        type: string
      binary_repo:
        required: true
        type: string

  # Enables manually running this workflow from the Actions tab
  workflow_dispatch:
    inputs:
      binary_version:
        required: true
        type: string
      binary_repo:
        required: true
        type: string

jobs:
  publish:
    name: Publish Artifact Bundle
    runs-on: macOS-13
    env:
      PLUGIN_VERSION: ${{ inputs.binary_version }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: Plugin-Repo
    - name: Get latest binaries
      run: |
          gh release download ${{ inputs.binary_version }} \
                            -R "${{ inputs.binary_repo }}" \
                            -p '*MacOS*64' \
                            -p '*Linux*64' \
                            -p '*Windows*64.exe' \
                            -p '*.deb' \
                            -p '*.rpm' \
                            -D 'Plugin-Repo/Resources/template.artifactbundle'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set info.json version
      run: |
          echo "${{ inputs.binary_version }}"
          PLUGIN_VERSION="${PLUGIN_VERSION#?}"
          echo "$PLUGIN_VERSION"
          sed -i '' "s/<VERSION>/$PLUGIN_VERSION/g" Plugin-Repo/Resources/template.artifactbundle/info.json
          cat Plugin-Repo/Resources/template.artifactbundle/info.json
