name: Publish Artifact Bundle

on:
  workflow_call:
    inputs:
      plugin_version:
        required: true
        type: string
      plugin_repo:
        required: true
        type: string

  # Enables manually running this workflow from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Publish Artifact Bundle
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v4
    - name: Get latest version
      run: |
          ls -a
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}