name: Publish Artifact Bundle

on:
  workflow_call:
    inputs:
      plugin_version:
        required: true
        type: string
      plugin_repo:
        required: true
        type: string

  # Enables manually running this workflow from the Actions tab
  workflow_dispatch:
    inputs:
      plugin_version:
        required: true
        type: string
      plugin_repo:
        required: true
        type: string

jobs:
  publish:
    name: Publish Artifact Bundle
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v4
      with:
        path: Plugin-Repo
    - name: Get latest binaries
      run: |
          gh release download ${{ inputs.plugin_version }} \
                            -R "${{ inputs.plugin_repo }}" \
                            -p '*MacOS*64' \
                            -p '*Linux*64' \
                            -p '*Windows*64.exe' \
                            -p '*.deb' \
                            -p '*.rpm' \
                            -D 'Plugin-Repo/Resources/template.artifactbundle'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set info.json version
      run: |
          echo "${{ inputs.plugin_version }}"
          sed -i '' "s/<VERSION>/${{ inputs.plugin_version }}/g" Plugin-Repo/Resources/template.artifactbundle/info.json
          cat Plugin-Repo/Resources/template.artifactbundle/info.json
